<?php
declare(strict_types=1);

namespace mdantas\PhinxWrap\Command;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class Init extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setDescription('Create a initialized dot .env file on root project!');
        $this->addArgument('path', InputArgument::OPTIONAL, 'path to puth env file template');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {

    }
}