<?php

return <<<EOT

###PHINX DATABASE CONFIGURATION###
DATABASE_MIGRATIONS_PATH=%%PHINX_CONFIG_DIR%%/db/migrations
DATABASE_SEEDS_PATH=%%PHINX_CONFIG_DIR%%/db/seeds
DATABASE_VERSION=creation
DATABASE_STAGE=development
DATABASE_ADAPTER=mysql
DATABASE_NAME=development_db
DATABASE_USER=root
DATABASE_PASSWORD=
DATABASE_HOST=localhost
DATABASE_PORT=3306
DATABASE_CHARSET=utf8

EOT;
